### ISSUE TITLE
Use official postgres image

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-gitlab#6]
Use the [official postgres image from DockerHub](https://hub.docker.com/_/postgres/) instead of [sameersbn/postgresql](https://hub.docker.com/r/sameersbn/postgresql/tags/), because that one was last built nine months ago.

`postgres` | `sameersbn/postgres`
---------------|---------------
`9.6.5` | `9.6-2`
`9.5.9` | `9.5-4`

The official image also supports the newly released PostgreSQL 10.

**Comment by jacksgt** [comment]
https://docs.gitlab.com/ce/install/requirements.html#postgresql-requirements

**Comment by jacksgt** [comment]
https://github.com/docker-library/docs/tree/master/postgres#how-to-extend-this-image
To avoid having to build one's own image, this could also be implemented by creating a script file on the host and mounting it into the image under `/docker-entrypoint-initdb.d/`:
```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE EXTENSION pg_trgm;
EOSQL
```

Or be very naughty and just use puppetlabs/puppetdb-postgres: https://github.com/puppetlabs/puppet-in-docker/blob/master/puppetdb-postgres/Dockerfile

**Comment by martialblog** [comment]
👍

**Comment by jacksgt** [comment]
Fixed in https://github.com/vision-it/vision-gitlab/commit/77672f697e8139483a459860e7fe1e1c4f05ad1c
Also upgraded to Postgres 9.6.8
